name: bidscoin
version: 4.6.2

copyright:
  - license: GPL-3.0-or-later
    url: https://github.com/Donders-Institute/bidscoin/blob/master/LICENSE.txt

architectures:
    - x86_64
    - aarch64

build:
    kind: neurodocker

    base-image: ubuntu:24.04

    pkg-manager: apt

    directives:
        - environment:
              DEBIAN_FRONTEND: noninteractive
              FSLDIR: /opt/miniconda-latest
              FSLOUTPUTTYPE: NIFTI_GZ

        - install:
              - ca-certificates   # Not sure what this is for
              - build-essential
              - pigz              # Speeds up dcm2niix
              - curl              # sometimes needed for dcm2niix
              - python3-pyqt6     # Avoid GUI issues
              - build-essential   # Needed for pip (needs gcc)
              - libgl1
              - libxcb-cursor0
              - tk
              - dbus
              - qt6-wayland       # Make sure wayland is supported

        - template:
            name: dcm2niix
            version: latest

        - template:
            name: bids_validator
            version: 1.13.0

        - template:
              name: miniconda
              conda_install: -c conda-forge -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/ fsl-libvis fsl-avwutils fsl-flirt
              pip_install: bidscoin[spec2nii2bids,deface]
              version: latest

        - test:
            name: Core function test
            script: bidscoin -t   # NB: Requires a graphical display

deploy:
    bins:
        - spec2nii
        - dcm2niix

# Test image with:
# sudo docker run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix bidscoin_${toolVersion}:TAG bidscoin -t
# sudo docker run -it -v /root:/root --entrypoint /bin/bash -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix bidscoin_${toolVersion}:TAG
# bidscoin -t

readme: |-
    ----------------------------------
    ## bidscoin/{{ context.version }} ##
    
    Contains a GUI and CLI tools needed for DICOM to BIDS conversion, as well as MRS spectroscopy and physiological data to BIDS conversion
  
    Tools included:
    ```
    dcm2niix: https://github.com/rordenlab/dcm2niix
    spec2nii: https://github.com/wtclarke/spec2nii
    bids-validator: https://github.com/bids-standard/bids-validator
    bidscoin: https://bidscoin.readthedocs.io/en/{{ context.version }}
      - bidscoin
      - bidscoiner
      - bidseditor
      - bidsmapper
      - bidsparticipants
      - deface
      - dicomsort
      - echocombine
      - medeface
      - physio2tsv
      - plotphysio
      - rawmapper
      - slicereport
      - fixmeta

    Example:
    ```
    ml bidscoin/{{ context.version }} bidscoin -h
    ```

    More documentation can be found here: https://bidscoin.readthedocs.io

    Citation:
    ```
    Zwiers MP, Moia S, Oostenveld R. BIDScoin: A User-Friendly Application to Convert Source Data to Brain Imaging Data Structure. Front Neuroinform. 2022 Jan 13;15:770608. doi: 10.3389/fninf.2021.770608. PMID: 35095452; PMCID: PMC8792932.
    ```

    To run container outside of this environment: ml bidscoin/{{ context.version }}

    ----------------------------------

categories:
  - "data organisation"
  - "bids apps"
